name: libre_skill_tree
description: "skill tree of life"
homepage: https://github.com/MD-DILDAR-MANDAL/libre_skill_tree
repository: https://github.com/MD-DILDAR-MANDAL/libre_skill_tree
issue_tracker: https://github.com/MD-DILDAR-MANDAL/libre_skill_tree/issues
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  build_runner: ^2.7.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  get_it: ^9.2.0
  graphx: ^1.0.14

  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0

  permission_handler: ^12.0.1
  share_plus: ^12.0.1

flutter_launcher_icons:
 image_path: "assets/icons/icon.png"
 android: true
 adaptive_icon_background: "assets/icons/background.png"
 adaptive_icon_foreground: "assets/icons/foreground.png"

dev_dependencies:
  isar_community_generator: ^3.3.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter_28pt-Medium.ttf
        - asset: assets/fonts/Inter_28pt-Bold.ttf

    - family: Oxanium
      fonts:
        - asset: assets/fonts/Oxanium-Regular.ttf
        - asset: assets/fonts/Oxanium-SemiBold.ttf
